### ISSUE TITLE
Apply commit message rule

### ISSUE THREAD

**Issue by hihiboss** [git-tturami/bike-android#22]
커밋이 너무 많고 메시지가 제각각이길래 커밋 메시지 룰 적용을 제안합니다 :)

참고
https://meetup.toast.com/posts/106
https://www.notion.so/junhuikim/Copy-of-iOS-Commit-Rule-27e76e4a81f841e8bd8ec2cbae6d6df2

**Comment by pingoo33** [comment]
감사합니다!
